In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b = np.array([[1,2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
a.shape

(3,)

In [10]:
a.dtype

dtype('int64')

In [11]:
a.ndim

1

In [12]:
a.size

3

In [13]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0], arr[-1], arr[1:4], arr[::2]) #first el, last el, slicing, every 2nd el

10 50 [20 30 40] [10 30 50]


In [19]:
matrix = np.array([[1,2], [3,4], [5,6]])
matrix[1, 0] # row 1 col 0
matrix[:, 1] # all rows, col 1

array([2, 4, 6])

In [17]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([1, 2, 3, 4, 5])

In [18]:
print(arr + 10, arr * 2, arr1 + arr2, arr1 - arr2)

[20 30 40 50 60] [ 20  40  60  80 100] [11 22 33 44 55] [ 9 18 27 36 45]


In [20]:
print(np.sqrt(arr), np.exp(arr), np.sin(arr))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781] [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21] [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]


In [21]:
print(np.min(arr), np.max(arr), np.mean(arr), np.sum(arr), np.median(arr), np.std(arr))

10 50 30.0 150 30.0 14.142135623730951


In [23]:
arr.reshape(5, 1)

array([[10],
       [20],
       [30],
       [40],
       [50]])

In [24]:
arr.T

array([10, 20, 30, 40, 50])

In [29]:
print(np.hstack((arr1, arr2)), np.vstack((arr1, arr2)), np.split(arr, 5))

[10 20 30 40 50  1  2  3  4  5] [[10 20 30 40 50]
 [ 1  2  3  4  5]] [array([10]), array([20]), array([30]), array([40]), array([50])]


In [31]:
arr[arr > 30]

array([40, 50])

In [33]:
arr[(arr > 20) & (arr < 60)]

array([30, 40, 50])

In [34]:
print(np.random.rand(3,3), np.random.randint(0, 10, size=(3,3)), np.random.seed(42))

[[0.65749154 0.83577123 0.99524021]
 [0.36926303 0.19463353 0.37675314]
 [0.82120821 0.70216547 0.94969167]] [[7 9 4]
 [4 0 5]
 [3 2 3]] None


In [35]:
arr = np.array([1,2,3])
arr + np.array([[1], [2], [3]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [36]:
np.sum(arr1 * arr2)

np.int64(550)

In [42]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [44]:
print(np.dot(arr1, arr2), np.linalg.det(matrix), np.linalg.eig(matrix))

550 0.0 EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [45]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])  # Singular

print("Determinant:", np.linalg.det(matrix))

try:
    print("Inverse:", np.linalg.inv(matrix))
except np.linalg.LinAlgError:
    print("Matrix is singular, using pseudoinverse instead:")
    print(np.linalg.pinv(matrix))

Determinant: 0.0
Matrix is singular, using pseudoinverse instead:
[[-6.38888889e-01 -1.66666667e-01  3.05555556e-01]
 [-5.55555556e-02  4.20756436e-17  5.55555556e-02]
 [ 5.27777778e-01  1.66666667e-01 -1.94444444e-01]]
